
on:
push:
branch:[main]
workflow_dispatch:
job:
build:
runs-on: ubuntu-latest:
steps:
-name: Checkout code
uses:actions/checkout@v2
-name: Setup Node.js
uses:actions/setup-node@v2
with:
node-version:'18'
-name: install dependancies
run:npm install
-name: Bulid application
run:echo"this is application"
test:
runs-on: ubuntu-latest:
need: Bulid
steps:
-name: Checkout code
uses: actions/checkout@v2
-name: install dependancies
run:npm install
-name: Run test
run: npm test
deploy:
runs-on: ubuntu-latest:
need: Test
steps:
-name: Checkout code
uses: actions/checkout@v2
-name: Deploy the application
run: echo"this is Deploy the application"
